README.rst, openedx_lti_tool_plugin/apps.py, openedx_lti_tool_plugin/edxapp_wrapper/__init__.py, openedx_lti_tool_plugin/edxapp_wrapper/backends/__init__.py, openedx_lti_tool_plugin/edxapp_wrapper/backends/courseware_module_o_v1.py, openedx_lti_tool_plugin/edxapp_wrapper/courseware_module.py, openedx_lti_tool_plugin/settings/common.py, openedx_lti_tool_plugin/settings/test.py, openedx_lti_tool_plugin/templates/openedx_lti_tool_plugin/courseware.html, openedx_lti_tool_plugin/tests/__init__.py, openedx_lti_tool_plugin/tests/backends_for_tests.py, openedx_lti_tool_plugin/tests/test_apps.py, openedx_lti_tool_plugin/tests/test_urls.py, openedx_lti_tool_plugin/tests/test_views.py, openedx_lti_tool_plugin/urls.py, openedx_lti_tool_plugin/views.py
https://agile-jira.pearson.com/browse/PADV-351
This PR adds XBlock and Courseware views for course LTI launches, this will allow us to have our own endpoints to render the course content for LTI launches with only the unit content. To achieve this we used the render_xblock function from edx-platform.
```
```
- Go to http://localhost:18000/openedx_lti_tool_plugin/course/unit_usage_key (Replace unit_usage_key with a XBlock ID of course unit).
- The browser should display the requested content on an iframe using the courseware.html template.
Currently the template only displays the content, we still need to render the course outline to let the user …
=> PADV-351: Add LTI XBlock and Courseware views

openedx_lti_tool_plugin/middleware.py, openedx_lti_tool_plugin/settings/common.py, openedx_lti_tool_plugin/tests/test_middleware.py
https://agile-jira.pearson.com/browse/PADV-353
This PR adds a LTI view permission middleware, this middleware is in charge of controlling access for LTI users (users with a LTI profile) to views on the platform, this will logout any LTI user trying to access a view other than the views on the LTI plugin, views required by XBlocks on edx-platform and/or third-party packages installed on edx-platform. Third-party packages XBlocks with views that should restricted by LTI users can add new blocklisted URL patterns to the OLTITP_URL_BLOCKLIST setting. Views on the edx-platform that should be whitelisted and are not on the default list can be added to the OLTITP_URL_WHITELIST setting.
- Add required settings to …
=> PADV-353: Add LTI view permission middleware

openedx_lti_tool_plugin/templates/openedx_lti_tool_plugin/course_home.html, openedx_lti_tool_plugin/templates/openedx_lti_tool_plugin/course_outline.html, openedx_lti_tool_plugin/templates/openedx_lti_tool_plugin/course_outline_item.html, openedx_lti_tool_plugin/templates/openedx_lti_tool_plugin/courseware.html, openedx_lti_tool_plugin/tests/test_urls.py, openedx_lti_tool_plugin/tests/test_views.py, openedx_lti_tool_plugin/urls.py, openedx_lti_tool_plugin/views.py
https://agile-jira.pearson.com/browse/PADV-381
This PR aims to add the functionality of navigating though the course while inside the courseware
[Screencast from 24-07-23 11:03:56.webm](https://github.com/Pearson-Advance/openedx-lti-tool-plugin/assets/62396424/a6268ff4-b924-4b40-b330-48f5061242b7)
[Screencast from 24-07-23 11:08:54.webm](https://github.com/Pearson-Advance/openedx-lti-tool-plugin/assets/62396424/71f2d248-637b-443e-9a2e-9b70d51e5b9e)
```
```
- Run ngrok or any other similar service: `ngrok http 18000`
- Create a new LTI 1.3 tool key config: http://localhost:18000/admin/lti1p3_tool_config/ltitoolkey/add/ (You can use IMS RI to create …
=> PADV 381 - Render courseware navigation

openedx_lti_tool_plugin/tests/test_urls.py, openedx_lti_tool_plugin/tests/test_views.py, openedx_lti_tool_plugin/urls.py, openedx_lti_tool_plugin/views.py
https://agile-jira.pearson.com/browse/PADV-363
This PR adds the ability to render both an entire course or a single unit or component. The approach taken was to verify the unit exists retrieving it from modulestore, using modulstore().get_item, then verify that the course ID of the object obtained matched the one specified in the launch and lastly verify the usage key is not a chapter nor sequential using the location.block_type attribute of the object. We decided to make it this way because modulestore bring us all the necessary things to do these validation, being this the most efficient way.
```
```
- Run ngrok or any other similar service: …
=> PADV 363 - Render single unit or component

openedx_lti_tool_plugin/middleware.py, openedx_lti_tool_plugin/settings/common.py, openedx_lti_tool_plugin/tests/test_middleware.py
https://agile-jira.pearson.com/browse/PADV-353
This PR improves the already implemented LTI view middleware to ease the debugging of blocked URLs, this PR also includes a new setting OLTITP_URL_WHITELIST_EXTRA that will allow us to extend the whitelisted URLs without replacing the URLs defined in the OLTITP_URL_WHITELIST setting.
```
OLTITP_URL_WHITELIST_EXTRA = ['/extra_path/']
```
- Run ngrok or any other similar service: `ngrok http 18000`
- Create a new LTI 1.3 tool key config: http://localhost:18000/admin/lti1p3_tool_config/ltitoolkey/add/ (You can use IMS RI to create a key pair: https://lti-ri.imsglobal.org/keygen/index)
- Create a new LTI …
=> PADV-353.1: LTI middleware logging, extra URLs setting

openedx_lti_tool_plugin/edxapp_wrapper/backends/modulestore_module_o_v1.py, openedx_lti_tool_plugin/edxapp_wrapper/modulestore_module.py, openedx_lti_tool_plugin/tests/test_utils.py, openedx_lti_tool_plugin/utils.py
https://agile-jira.pearson.com/browse/PADV-658
This PR applies a fix to filter out the units that are not yet published. After some discussion on how we are obtaining the outline data, we came to the conclusion of applying this fix to cover this case and make a further work on re-implementing the course outline and navigation functionalities for a LTI launch in such a way that the performance impact is reduced to minimum.
```
```
- Run ngrok or any other similar service: `ngrok http 18000`
- Create a new LTI 1.3 tool key config: http://localhost:18000/admin/lti1p3_tool_config/ltitoolkey/add/ (You can use IMS RI to create a key pair: …
=> PADV 658 - Filter unavailable units on course outline

openedx_lti_tool_plugin/http.py, openedx_lti_tool_plugin/middleware.py, openedx_lti_tool_plugin/models.py, openedx_lti_tool_plugin/tests/test_http.py, openedx_lti_tool_plugin/tests/test_middleware.py, openedx_lti_tool_plugin/tests/test_models.py, openedx_lti_tool_plugin/tests/test_views.py, openedx_lti_tool_plugin/views.py
https://agile-jira.pearson.com/browse/PADV-690
This PR improves the response handling of LTI views to allow them return clearer messages on errors while also logging the error on the LMS logs for further debugging. This also includes a fix of the allowed_course_ids field on the CourseAccessConfiguration model and also an improvement on the logout log message of the LTI middleware. 
```
```
- Run ngrok or any other similar service: `ngrok http 18000`
- Create a new LTI 1.3 tool key config: http://localhost:18000/admin/lti1p3_tool_config/ltitoolkey/add/ (You can use IMS RI to create a key pair: https://lti-ri.imsglobal.org/keygen/index)
- Create a …
=> PADV-690: Improve log, response messages

README.rst, openedx_lti_tool_plugin/settings/common.py
Once this plugin is installed, it modifies the `AUTHENTICATION_BACKENDS` platform variable. Following the open for extension, but closed for modification principle, this PR stops adding the `LtiAuthenticationBackend` class to `AUTHENTICATION_BACKENDS`, so this setting is handled at configuration settings. The corresponding setting is being added here: https://github.com/Pearson-Advance/tutor-pearson-plugin/pull/98
=> refactor: remove AUTHENTICATION_BACKENDS modification. 

openedx_lti_tool_plugin/auth.py, openedx_lti_tool_plugin/signals.py, openedx_lti_tool_plugin/tests/test_auth.py, openedx_lti_tool_plugin/tests/test_signals.py, openedx_lti_tool_plugin/utils.py, openedx_lti_tool_plugin/views.py
This PR add a new function is_plugin_enabled to improve the OLTITP_ENABLE_LTI_TOOL setting check handling on parts of the plugin that requires to verify if the plugin is enabled or not. This PR also includes an improvement to the LtiAuthenticationBackend to verify if the plugin is enabled before executing any authentication code. Additionally this PR also includes minor improvements to a few plugin unit tests.
- Setup the plugin: https://github.com/Pearson-Advance/openedx-lti-tool-plugin#installation-on-open-edx-devstack
- Setup a resource launch on a LTI platform: https://github.com/Pearson-Advance/openedx-lti-tool-plugin#lti-13-resource-launch-setup
- Set OLTITP_ENABLE_LTI_TOOL setting to True.
- Execute the LTI launch.
- The LTI launch should work and authenticate the user.
- Set …
=> feat: Improve OLTITP_ENABLE_LTI_TOOL check handling

Makefile, openedx_lti_tool_plugin/signals.py, openedx_lti_tool_plugin/tests/test_signals.py
- https://agile-jira.pearson.com/browse/PADV-1128
This PR adds improvements to the AGS callback on course launches, this PR removes the limit of AGS score update callbacks by allowing score updates on any course grade that has any percent value, additionally this PR removes the call for the clean command on the quality and test Makefile command, this command was uninstalling the plugin from the development environment thus making harder debugging after local CI tests.
- Modify update_course_score function on signals.py module.
- Remove clean command from quality and test Makefile commands.
- Add or modify any unit test for all related code.
=> PADV-1128: Improve AGS callback

openedx_lti_tool_plugin/deep_linking/__init__.py, openedx_lti_tool_plugin/deep_linking/exceptions.py, openedx_lti_tool_plugin/deep_linking/tests/__init__.py, openedx_lti_tool_plugin/deep_linking/tests/test_urls.py, openedx_lti_tool_plugin/deep_linking/tests/test_views.py, openedx_lti_tool_plugin/deep_linking/urls.py, openedx_lti_tool_plugin/deep_linking/views.py, openedx_lti_tool_plugin/tests/test_views.py, openedx_lti_tool_plugin/urls.py, openedx_lti_tool_plugin/views.py
https://agile-jira.pearson.com/browse/PADV-1190
This PR adds the views for the Deep Linking feature, currently the view can be interacted with a Deep Linking request but there is still some development pending to be done on these views that will be addressed on PADV-1191 that will allow to use the views on a complete Deep Linking UI workflow. 
- Run ngrok or any other similar service on LMS: `ngrok http 18000`
```
```
- Create a new LTI 1.3 tool key config: http://localhost:18000/admin/lti1p3_tool_config/ltitoolkey/add/ (You can use IMS RI to create a key pair: https://lti-ri.imsglobal.org/keygen/index)
- Create a new LTI 1.3 tool config: …
=> PADV-1190: Add Deep Linking views.

openedx_lti_tool_plugin/deep_linking/forms.py, openedx_lti_tool_plugin/deep_linking/tests/test_forms.py, openedx_lti_tool_plugin/deep_linking/tests/test_views.py, openedx_lti_tool_plugin/deep_linking/views.py, openedx_lti_tool_plugin/resource_link_launch/views.py, openedx_lti_tool_plugin/tests/test_utils.py, openedx_lti_tool_plugin/utils.py
https://agile-jira.pearson.com/browse/PADV-1201
This PR adds a filter to the courses available on the DeepLinkingForm. This PR adds a DeepLinkingForm method that either returns all CourseContext objects with all courses on the LMS or a filtered CourseContext queryset with only the courses available per LtiTool using the CourseAccesConfiguration allowed_course_ids field.
- Run ngrok or any other similar service on LMS: `ngrok http 18000`
```
```
- Create a new LTI 1.3 tool key config: http://localhost:18000/admin/lti1p3_tool_config/ltitoolkey/add/ (You can use IMS RI to create a key pair: https://lti-ri.imsglobal.org/keygen/index)
- Create a new …
=> PADV-1201: Filter courses in DeepLinkingForm

openedx_lti_tool_plugin/models.py, openedx_lti_tool_plugin/resource_link_launch/tests/test_views.py, openedx_lti_tool_plugin/resource_link_launch/views.py, openedx_lti_tool_plugin/tests/test_models.py, openedx_lti_tool_plugin/tests/test_utils.py, openedx_lti_tool_plugin/utils.py
- https://agile-jira.pearson.com/browse/PADV-717
This PR adds the ability to use the "Given name", "Middle name", "Family name", or "Full name" PII claims on the `LtiProfile` `user` profile. This PR also includes various improvements to the handling of the `LtiProfile` save method, the handling of PII data updates, the claims obtained by the `get_pii_from_claims` function and the `ResourceLinkLaunchView` `post` method.
- Run the learning MFE on the host machine: `npm run start`.
- Run ngrok or any other similar service on LMS: `ngrok http 18000`
- Run ngrok or any other similar service on learning MFE: `ngrok http 2000`
```
SHARED_COOKIE_DOMAIN = …
```
=> PADV-717: Use PII data on LtiProfile user

openedx_lti_tool_plugin/models.py, openedx_lti_tool_plugin/tests/test_models.py, requirements/base.in, requirements/base.txt, requirements/test.txt
- https://agile-jira.pearson.com/browse/PADV-1394
This PR improves the generation of the LtiProfile user, more specifically the LtiProfile user username and email structure, additionally the LtiProfile name property was modified and the name used on the user profile was truncated to 255 characters in case a very large name is used to avoid error with the field max_length.
```
SHARED_COOKIE_DOMAIN = ".ngrok.io"  # Replace .ngrok.io with the …
```
=> PADV-1394: Improve LTI profile user

openedx_lti_tool_plugin/deep_linking/forms.py, openedx_lti_tool_plugin/deep_linking/tests/test_forms.py, openedx_lti_tool_plugin/deep_linking/tests/test_views.py, openedx_lti_tool_plugin/deep_linking/views.py, openedx_lti_tool_plugin/models.py, openedx_lti_tool_plugin/settings/common.py, openedx_lti_tool_plugin/settings/test.py, openedx_lti_tool_plugin/tests/backends_for_tests.py, openedx_lti_tool_plugin/tests/test_models.py
https://agile-jira.pearson.com/browse/PADV-1423
This PR adds a feature that allows obtain the choices of the DeepLinkingForm content_items field from a function set on the OLTITP_DL_CONTENT_ITEMS_PROVIDER setting, this setting can be set to the path of a provider function that is available on the LMS environment, this function must receive a request and launch_data argument and return a list of dictionaries containing [content item data](https://www.imsglobal.org/spec/lti-dl/v2p0#content-item-types).
Additionally this PR also includes a refactoring of the DeepLinkingForm class and an improvement on various test names and docstrings from tests that where modified, this refactor was done in order to be able to include this feature and to also improve the form handling of the content items …
=> PADV-1423: Get DeepLinkingForm content_items choices from provider function

openedx_lti_tool_plugin/models.py, openedx_lti_tool_plugin/tests/test_models.py
- https://agile-jira.pearson.com/browse/PADV-1574
This PR improves the generation of the LtiProfile user, more specifically the LtiProfile user username and name properties. The name property was modified to make use of the [name PII claim](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) if present and the username property was modified to clean it against a regex to make sure the given_name and family_name values don't contain values that will generate issues with [UnicodeUsernameValidator](https://docs.djangoproject.com/en/3.2/ref/contrib/auth/#django.contrib.auth.validators.UnicodeUsernameValidator) used on the User username field.
3. Install `openedx_lti_tool_plugin` …
=> PADV-1574: Improve LtiProfile name and username property

openedx_lti_tool_plugin/apps.py, openedx_lti_tool_plugin/models.py, openedx_lti_tool_plugin/tests/test_apps.py, openedx_lti_tool_plugin/tests/test_models.py
- https://agile-jira.pearson.com/browse/PADV-1854
This PR improves the generation of the LtiProfile user, more specifically the LtiProfile user email property. The email property was modified to contain a top-level domain in his address to avoid issues with the regex validation of [EmailValidator](https://docs.djangoproject.com/en/5.1/ref/validators/#emailvalidator). 
```
SHARED_COOKIE_DOMAIN = ".ngrok.io"  # Replace .ngrok.io with the …
```
=> PADV-1854: LtiProfile email domain

openedx_lti_tool_plugin/models.py, openedx_lti_tool_plugin/tests/test_models.py
- https://agile-jira.pearson.com/browse/PADV-1922
This PR improves the generation of the LtiProfile user, more specifically the LtiProfile user username and name properties. The username property was modified to clean it against a regex that removes all special characters some of which weren't covered before, also the process to obtain the name used on the username was modified to use the values from the name property instead of using the `pii` given_name and family_name value, the name property docstrings were also modified.
5. Run ngrok or any other similar service on …
=> PADV-1922: Improve LtiProfile username generation

openedx_lti_tool_plugin/deep_linking/views.py, openedx_lti_tool_plugin/views.py
https://agile-jira.pearson.com/browse/PADV-2048
This PR adds the `xframe_options_exempt` to the `DeepLinkingFormView` and `LtiToolLoginView` to make these views exempt from the X-Frame-Options DENY HTTP header added to the views response by the Django `XFrameOptionsMiddleware`.
2. Install `openedx_lti_tool_plugin` on the LMS.
3. Run ngrok or any other similar service on LMS: `ngrok http 18000`
4. Add required settings to LMS.
```python
```
5. Create a new LTI 1.3 tool key config: https://lms.ngrok.io/admin/lti1p3_tool_config/ltitoolkey/add/ (You can use IMS RI to create a key pair: https://lti-ri.imsglobal.org/keygen/index)
6. Create a new LTI 1.3 tool config: https://lms.ngrok.io/admin/lti1p3_tool_config/ltitool/add/
``` …
```
=> PADV-2048: Remove X-Frame-Options from DeepLinkingFormView, LtiToolLoginView

openedx_lti_tool_plugin/deep_linking/api/v1/serializers.py, openedx_lti_tool_plugin/deep_linking/api/v1/tests/test_serializers.py, openedx_lti_tool_plugin/deep_linking/forms.py, openedx_lti_tool_plugin/deep_linking/tests/test_forms.py, openedx_lti_tool_plugin/deep_linking/tests/test_utils.py, openedx_lti_tool_plugin/deep_linking/utils.py, openedx_lti_tool_plugin/resource_link_launch/tests/test_urls.py, openedx_lti_tool_plugin/resource_link_launch/tests/test_views.py, openedx_lti_tool_plugin/resource_link_launch/urls.py, openedx_lti_tool_plugin/resource_link_launch/views.py
- https://agile-jira.pearson.com/browse/PADV-2053
This PR improves the resource ID handling on ResourceLinkLaunchView and the Deep Linking workflow. Currently ResourceLinkLaunchView determines the requested resource by obtaining the course ID and/or the usage key of a unit/component from the URL pattern of this view, this PR improves these by making the URL pattern receive a single resource ID that can either be a course ID or usage key, this can be optional since the resource ID can also be retrieved from the `resource_id` key value from the LTI custom parameters. The Deep Linking workflow was also updated to include the resource ID on the content item custom parameters instead of including it on the URL path. This was created to make an easier integration with the Deep Linking service …
=> PADV-2053: Improve ResourceLinkLaunchView and Deep Linking resource ID handling

openedx_lti_tool_plugin/admin.py, openedx_lti_tool_plugin/tests/test_admin.py
- https://agile-jira.pearson.com/browse/PADV-2211
This PR improves the Django admin configuration of the LtiProfile. This PR adds the user ID and user email to the list columns, adds the user email to the search fields and additionally adds the LtiProfile uuid and user had read-only fields while editing an LtiProfile.
2. Go to http://localhost:18000/admin/openedx_lti_tool_plugin/ltiprofile
3. Verify the user ID and user email are present on the list columns.
4. Verify the Django admin can search using the LtiProfile user email.
5. Verify the uuid and user are shown while modifying an LtiProfile.
=> PADV-2211: Improve LtiProfile admin configuration

.github/workflows/ci.yml
This PR fixes the issue related to the retirement of the Ubuntu 20.04 LTS runner, the runner was removed on 2025-04-15 making our CI workflow fail. For more details, see https://github.com/actions/runner-images/issues/11101. Additionally the checkout and Python setup steps where updated to newer versions.
=> fix: CI GitHub Workflow

openedx_lti_tool_plugin/deep_linking/exceptions.py, openedx_lti_tool_plugin/deep_linking/tests/test_views.py, openedx_lti_tool_plugin/deep_linking/views.py, openedx_lti_tool_plugin/exceptions.py, openedx_lti_tool_plugin/mixins.py, openedx_lti_tool_plugin/models.py, openedx_lti_tool_plugin/resource_link_launch/exceptions.py, openedx_lti_tool_plugin/resource_link_launch/tests/test_utils.py, openedx_lti_tool_plugin/resource_link_launch/tests/test_views.py, openedx_lti_tool_plugin/resource_link_launch/utils.py, openedx_lti_tool_plugin/resource_link_launch/views.py, openedx_lti_tool_plugin/templates/openedx_lti_tool_plugin/resource_link/login_prompt.html, openedx_lti_tool_plugin/tests/test_mixins.py, openedx_lti_tool_plugin/tests/test_models.py
- https://agile-jira.pearson.com/browse/PADV-2213
This PR adds the functionality for user provisioning modes to the ResourceLinkLaunchView, additionally a get_message method was added to the LTIToolMixin and the DeepLinkingView was updated to make use of such method, additionally the DeepLinkingException was updated to inherit from the LtiToolException class and the docstrings of the modified code was updated.
```
SHARED_COOKIE_DOMAIN = …
```
=> PADV-2213: Add ResourceLinkLaunchView user provisioning mode feature

openedx_lti_tool_plugin/templates/openedx_lti_tool_plugin/resource_link/login_prompt.html
- https://agile-jira.pearson.com/browse/PADV-2309
This PR modifies the login_prompt.html template to include a message requesting the user to either link an existing account or let the plugin create an account for them, this template is rendered by the ResourceLinkLaunchView when the get_or_create_lti_profile method of such view doesn't return an LtiProfile instance.
```
SHARED_COOKIE_DOMAIN = ".ngrok.io"  # Replace .ngrok.io with the …
```
=> PADV-2309: Modify login_prompt.html template

openedx_lti_tool_plugin/resource_link_launch/tests/test_views.py, openedx_lti_tool_plugin/resource_link_launch/views.py, openedx_lti_tool_plugin/templates/openedx_lti_tool_plugin/resource_link/login_prompt.html
- https://agile-jira.pearson.com/browse/PADV-2340
This PR modifies the user provisioning feature to make use of the PII email while linking an user, this will make sure that learners cannot link an user with a different email from the email sent on the PII data, if the PII email is not present then there will be no restriction.
```
SHARED_COOKIE_DOMAIN = ".ngrok.io"  # Replace .ngrok.io with the domain of the service used to expose the LMS …
```
=> PADV-2340: Make user provision use PII email on link

openedx_lti_tool_plugin/resource_link_launch/tests/test_views.py, openedx_lti_tool_plugin/resource_link_launch/views.py, openedx_lti_tool_plugin/settings/common.py, openedx_lti_tool_plugin/settings/test.py
- https://pearson.atlassian.net/browse/PADV-2342
This PR adds a `OLTITP_LOGIN_PROMPT_TEMPLATE` setting that allows modifying the template used for the user provisioning feature in LTI 1.3 resource link launches.
```
OLTITP_LOGIN_PROMPT_TEMPLATE = 'test/template.html'  
SHARED_COOKIE_DOMAIN = ".ngrok.io"  # Replace .ngrok.io with the domain of the service used to expose the LMS and learning MFE if using another service other than ngrok. …
```
=> PADV-2342: Add user provisioning template  setting
